openapi: 3.0.0
info:
  version: v2
  title: Echo Server
  description: A Simple Echo API

servers:
  - url: http://echo-server:8080/v2
    description: Kong Production API Gateway Interface

paths:
  /v2/echo:
    get:
      description: Returns an echo
      responses:
        '200':
          description: Successfully returns an echo
        '500':
          $ref: '#/components/responses/500Error'
    post:
      description: Returns a POST body echo
      responses:
        '200':
          description: Successfully returns an echo
        '500':
          $ref: '#/components/responses/500Error'
  /v2/print:
    get:
      description: Get Print Jobs
      responses:
        '200':
          description: Successfully returns print jobs
        '500':
          $ref: '#/components/responses/500Error'
    post:
      description: Start a Print Job
      responses:
        '200':
          description: Successfully starts a print job
        '500':
          $ref: '#/components/responses/500Error'
components:
  responses:
    500Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
