openapi: 3.0.0
info:
  version: v1
  title: Echo Server with-dashes with_underscores with.dots
  description: A Simple Echo API
servers:
  - url: http://echo-server:8080/v1
    description: Kong Production API Gateway Interface
paths:
  /v1/echo:
    get:
      x-kong-name: "jack-echo_GET_ALL"
      operationId: "echoGetAll"
      description: Returns an echo
      responses:
        '200':
          description: Successfully returns an echo
        '500':
          $ref: '#/components/responses/500Error'
  /v1/echo/{user_id}:
    get:
      x-kong-name: "jack-echo_GET"
      operationId: "echoGet"
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string

      description: Returns an echo
      responses:
        '200':
          description: Successfully returns an echo
        '500':
          $ref: '#/components/responses/500Error'
    post:
      operationId: "echoPost"
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
      description: Returns a POST body echo
      responses:
        '200':
          description: Successfully returns an echo
        '500':
          $ref: '#/components/responses/500Error'
components:
  responses:
    500Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
