name: Deployment

on:
  workflow_dispatch: {}
    # inputs:
    #   environment:
    #     type: choice
    #     description: Select target environment
    #     options:
    #     - nonprod
    #     - prod

jobs:
  sync-dev:
    environment:
      name: dev

    runs-on: ubuntu-latest
    container:
      image: kong/deck:v1.35.0
      options: "--user root --cpus 1"
      volumes:
        - ./:/repository

    steps:
      - uses: actions/checkout@v2
      
      - name: Deck Sync on dev
        run: |
          This would be a sync


  sync-nonprod:
    environment:
      name: nonprod

    needs: sync-dev

    runs-on: ubuntu-latest
    container:
      image: kong/deck:v1.35.0
      options: "--user root --cpus 1"
      volumes:
        - ./:/repository

    steps:
      - uses: actions/checkout@v2
      
      - name: Deck Sync on nonprod
        run: |
          This would be a sync to nonprod

  sync-prod:
    environment:
      name: prod

    needs: sync-nonprod

    runs-on: ubuntu-latest
    container:
      image: kong/deck:v1.35.0
      options: "--user root --cpus 1"
      volumes:
        - ./:/repository

    steps:
      - uses: actions/checkout@v2
      
      - name: Deck Sync on prod
        run: |
          This would be a sync to prod
