name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select target environment
        options:
        - nonprod
        - prod

jobs:
  diff:
    environment:
      name: ${{ inputs.environment }}

    runs-on: ubuntu-latest
    container:
      image: kong/deck:v1.35.0
      options: "--user root --cpus 1"
      volumes:
        - ./:/repository

    steps:
      - uses: actions/checkout@v2
      
      - name: deck-diff on ${{ inputs.environment }} env
        run: |
          This would be a diff


  sync:
    environment:
      name: ${{ inputs.environment }}

    runs-on: ubuntu-latest
    container:
      image: kong/deck:v1.35.0
      options: "--user root --cpus 1"
      volumes:
        - ./:/repository

    steps:
      - uses: actions/checkout@v2
      
      - name: deck-sync on ${{ inputs.environment }} env
        run: |
          This would be a sync

      # - name: greet
      #   run: | 
      #     echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
      #     echo "CP NAME IS ${{ vars.KONNECT_CONTROL_PLANE_NAME }}"
