name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: '[nonprod],prod'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: kong/deck:v1.35.0
      options: "--user root --cpus 1"
      volumes:
        - ./:/repository

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
