name: create-release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "Create Release"

    runs-on: "ubuntu-latest"
    container:
      image: ubuntu:22.04
      options: "--user root --cpus 1"  # run as root doesn't matter, we can't do any damage to GitHub
      volumes:
        - ./:/repository

    steps:
      - name: "Determine tag"
        run: "echo \"RELEASE_TAG=1.0.0\" >> $GITHUB_ENV"

      - name: "Create release"
        uses: "actions/github-script@v6"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_TAG,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
              });

              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }
