name: pull-request
on:
  - pull_request
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: busybox
      env:
        KONNECT_API_KEY_NONPROD: ${{ secrets.KONNECT_API_KEY_NONPROD }}  
      volumes:
        - ./:/host
      options: --cpus 1
    steps:
      - name: Hi
        run: |
          echo $KONNECT_API_KEY_NONPROD
